//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import com.github.braully.persistence.IEntity;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@MappedSuperclass
public abstract class AbstractExpirableEntity
        extends AbstractEntity implements IEntity, Serializable {

    @Basic
    protected Date dateBegin;

    @Basic
    protected Date dateEnd;

    public Date getDateBegin() {
        return this.dateBegin;
    }

    public void setDateBegin(Date dateBegin) {
        this.dateBegin = dateBegin;
    }

    public Date getDateEnd() {
        return this.dateEnd;
    }

    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }

    @Override
    public boolean isPersisted() {
        return this.id != null && this.id > 0;
    }

    @Override
    public String toString() {
        return this.getClass().getSimpleName() + " (" + "#" + id + ')';
    }
}
