//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import com.github.braully.constant.Attr;
import com.github.braully.persistence.IEntity;
import com.github.braully.persistence.IMigrableEntity;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@MappedSuperclass
public abstract class AbstractMigrableEntity extends AbstractEntity implements IEntity, Serializable, IMigrableEntity {

    @Column(unique = true)
    @Basic
    @Attr("hidden")
    protected String uniqueCode;

    public AbstractMigrableEntity() {

    }

    @Override
    public String getUniqueCode() {
        return this.uniqueCode;
    }

    @Override
    public void setUniqueCode(String uniqueCode) {
        this.uniqueCode = uniqueCode;
    }

    @Override
    public boolean isPersisted() {
        return this.id != null && this.id > 0;
    }
}
