//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
@Table(schema = "base")
public class Email extends AbstractLightRemoveEntity implements Serializable {

    @Basic
    protected String type;

    @Basic
    protected String value;

    public Email() {

    }

    @Override
    public String toString() {
        return value;
    }
}
