//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
@Table(schema = "sale")
public class InventoryItem extends AbstractEntity implements Serializable {

    @ManyToOne(targetEntity = Product.class)
    protected Product product;

    @Basic
    protected String quantity;

    @ManyToOne(targetEntity = Partner.class)
    protected Partner supplier;

    @Basic
    protected String name;

    @Basic
    protected String type;

    @ManyToOne(targetEntity = Inventory.class)
    protected Inventory inventory;

    public InventoryItem() {

    }

}
