//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
@Entity
@Table(name = "menu", schema = "security")
public class Menu extends AbstractLightRemoveEntity implements Serializable {

    @Basic
    protected Integer sortIndex;

    @Basic
    protected String name;

    @Basic
    protected String link;

    @Basic
    protected String icon;

    @OneToMany(targetEntity = Menu.class, mappedBy = "parent")
    protected List<Menu> childs;

    @ManyToOne
    protected Menu parent;

    @Basic
    protected String value;

    public Menu() {

    }

    public Menu(String menu) {
        this.value = menu;
        this.name = menu;
    }

    public List<Menu> getChildsActive() {
        return (List<Menu>) this.cache().getMap()
                .computeIfAbsent("childsActive",
                        k -> this.childs.stream()
                                .filter(v -> v.getActive()).collect(Collectors.toList()));
    }

    public List<Menu> getChilds() {
        return this.childs;
    }

//    @JsonIgnore
    public Menu getPai() {
        return parent;
    }

    public void setPai(Menu pai) {
        this.parent = pai;
    }

    public Menu addChild(Menu menu) {
        if (this.childs == null) {
            this.childs = new ArrayList<>();
        }
        this.childs.add(menu);
        return this;
    }

    public Menu link(String link) {
        this.link = link;
        return this;
    }
}
