//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Enterprise or Team.
 *
 */
@Table(schema = "base")
@Entity
public class PartnerGroup extends AbstractEntity implements Serializable {

    @ManyToMany(targetEntity = Partner.class)
    @JoinTable(schema = "base")
    protected List<Partner> partners;

    @Basic
    protected String name;

    @Basic
    protected String description;

    @Basic
    protected String type;

    public PartnerGroup() {

    }

}
