//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.util.Objects;

public class PartnerPartnerPK implements Serializable {

    protected Long partnerTarget;

    protected Long partnerSource;

    protected Long id;

    public PartnerPartnerPK() {

    }

    public Long getPartnerTarget() {
        return this.partnerTarget;
    }

    public void setPartnerTarget(Long partnerTarget) {
        this.partnerTarget = partnerTarget;
    }

    public Long getPartnerSource() {
        return this.partnerSource;
    }

    public void setPartnerSource(Long partnerSource) {
        this.partnerSource = partnerSource;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + Objects.hashCode(this.partnerTarget);
        hash = 59 * hash + Objects.hashCode(this.partnerSource);
        hash = 59 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PartnerPartnerPK other = (PartnerPartnerPK) obj;
        if (!Objects.equals(this.partnerTarget, other.partnerTarget)) {
            return false;
        }
        if (!Objects.equals(this.partnerSource, other.partnerSource)) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

}
