//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import com.github.braully.util.UtilValidation;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
@Table(schema = "base")
@DiscriminatorValue("0")
@DiscriminatorColumn(discriminatorType = DiscriminatorType.INTEGER,
        name = "type_id", columnDefinition = "smallint default '0'", length = 1)
public class Phone extends AbstractLightRemoveEntity implements Serializable {

    @Basic
    protected String number;

    @Basic
    protected String observation;

    @Basic
    protected String type;

    public Phone() {

    }

    public String format() {
        return number + (UtilValidation.isStringValid(type) ? " (" + type + ")" : "");
    }

    @Override
    public String toString() {
        return format();
    }

    public Phone number(String numero) {
        this.number = numero;
        return this;
    }

    public Phone type(String type) {
        this.type = type;
        return this;
    }
}
