//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(schema = "sale")
@Getter
@Setter
public class ProductPrice extends AbstractExpirableEntity implements Serializable {

    @ManyToOne
    protected Organization organization;

    @ManyToOne(targetEntity = Inventory.class)
    protected Inventory inventory;

    @ManyToOne(targetEntity = Product.class)
    protected Product product;

    protected String description;

    @Basic
    protected BigDecimal basePrice;

    @Basic
    protected BigDecimal fixedPrice;

    @Basic
    protected BigDecimal charge;

    @Basic
    protected Double taxPercent;

    @Basic
    protected Double profitPercent;

}
