//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.util.Collection;
import java.util.List;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
@Table(name = "role", schema = "security")
//@Access(AccessType.FIELD)
public class Role extends AbstractGlobalEntity implements Serializable {

    public Role() {

    }

    public Role(String name) {
        this.name = name;
    }

    public Role name(String name) {
        this.name = name;
        return this;
    }

    @ManyToOne
    protected Role parent;

    @OneToMany(mappedBy = "parent")
    protected Set<Role> childs;

    @Basic
    protected String name;

    @Basic
    protected String description;

    @Basic
    @Enumerated
    protected SysRole sysRole;

    @ManyToMany(targetEntity = Menu.class, fetch = FetchType.EAGER)
    @JoinTable(name = "role_menu", schema = "security", joinColumns
            = @JoinColumn(name = "fk_role", referencedColumnName = "id"),
            inverseJoinColumns
            = @JoinColumn(name = "fk_menu", referencedColumnName = "id"))
    protected List<Menu> menus;

    public Menu[] getMenusArray() {
        Menu[] arr = null;
        Collection<Menu> mns = this.getMenus();
        if (mns != null) {
            arr = this.menus.toArray(new Menu[0]);
        }
        return arr;
    }

    public void setMenusArray(Menu[] mns) {
        Collection<Menu> menus1 = this.getMenus();
        menus1.clear();
        if (mns != null) {
            for (Menu m : mns) {
                menus1.add(m);
            }
        }
    }

    //Spring security    @Override
    public String getAuthority() {
        return this.name;
    }

    @Override
    public String toString() {
        return name + " (" + this.id + ")";
    }
}
